apiVersion: v1
kind: Service
metadata:
  name: falcosidekick-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: falcosidekick-ui
    app.kubernetes.io/name: falcosidekick-ui
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 2802
      targetPort: 2802
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30010
