apiVersion: v1
kind: Service
metadata:
  name: webapp-gateway
  namespace: default
  labels:
    app: webapp-gateway
spec:
  selector:
    app: webapp-gateway
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
