apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: default
spec:
  version: 8.2.1
  count: 2
  elasticsearchRef:
    name: elasticsearch
  
  podTemplate:
      spec:
        nodeSelector:
          node-name: master-3
          
  http:
    tls:
      selfSignedCertificate:
        disabled: true
