apiVersion: v1
kind: Service
metadata:
  name: webapp-uaa
  namespace: default
  labels:
    app: webapp-uaa
spec:
  selector:
    app: webapp-uaa
  type: LoadBalancer
  ports:
    - name: http
      port: 9999
