apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-uaa
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-uaa
      version: "v1"
  template:
    metadata:
      labels:
        app: webapp-uaa
        version: "v1"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - webapp-uaa
                topologyKey: kubernetes.io/hostname
              weight: 100
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
            - "/bin/sh"
            - "-c"
            - |
              while true
              do
                if [ $? -eq 0 ]; then
                  echo "DB is UP"
                  break
                fi
                echo "DB is not yet reachable;sleep for 10s before retry"
                sleep 10
              done
      containers:
        - name: webapp-uaa-app
          image: localhost:8083/registry/techinstinct/sirh-uaa:0.0.69
          env:
            - name: APPLICATION_GOOGLE_RECAPTCHA_CHECK
              value: "false"
            - name: APPLICATION_GOOGLE_RECAPTCHA_KEY_SECRET
              value: "6LfxCaUZAAAAAOGPqYosDlhVa6NRSvHCdLwB6V9_"
            - name: JDK_JAVA_OPTIONS
              value: " --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/config
            - name: JHIPSTER_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: registry-secret
                  key: registry-admin-password
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/eureka/
            - name: SPRING_SLEUTH_PROPAGATION_KEYS
              value: "x-request-id,x-ot-span-context"
            - name: SERVER_SHUTDOWN
              value: graceful
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: com.ti.sirh
            - name: ELASTIC_APM_SERVICE_NAME
              value: SIRH_STAGING_UAA
            - name: ELASTIC_APM_SERVER_URLS
              value: http://apm-server-apm-http:8200
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apm-server-apm-token
                  key: secret-token
            - name: SPRING_RABBITMQ_ADDRESSES
              value: "rabbitmqcluster:5672"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmqcluster"
            - name: SPRING_RABBITMQ_VIRTUAL-HOST
              value: techin
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmqcluster-default-user
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmqcluster-default-user
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://patronidemo:5432/uaa"
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: patronidemo
                  key: superuser-password
            - name: SPRING_MAIL_HOST
              value: "smtp.gmail.com"
            - name: SPRING_MAIL_PORT
              value: "587"
            - name: SPRING_MAIL_USERNAME
              value: "tech.intinct.k8s"
            - name: SPRING_MAIL_PASSWORD
              value: "Thesisk8s"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "true"

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - name: http
              containerPort: 9999
