apiVersion: v1
kind: Service
metadata:
  name: webapp-facturation
  namespace: default
  labels:
    app: webapp-facturation
spec:
  selector:
    app: webapp-facturation
  type: LoadBalancer
  ports:
    - name: http
      port: 4202
