apiVersion: apps/v1
kind: Deployment
metadata:
  name: companymanagement
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: companymanagement
      version: "v1"
  template:
    metadata:
      labels:
        app: companymanagement
        version: "v1"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - companymanagement
                topologyKey: kubernetes.io/hostname
              weight: 100
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
            - "/bin/sh"
            - "-c"
            - |
              while true
              do
                rt=$(nc -z -w 1 patronidemo 5432)
                if [ $? -eq 0 ]; then
                  echo "DB is UP"
                  break
                fi
                echo "DB is not yet reachable;sleep for 10s before retry"
                sleep 10
              done
      containers:
        - name: companymanagement-app
          image: localhost:8083/registry/techinstinct/sirh-company-management:0.0.190
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/config
            - name: JHIPSTER_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: registry-secret
                  key: registry-admin-password
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://patronidemo:5432/companymanagement
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: patronidemo
                  key: superuser-password
            - name: SPRING_LIQUIBASE_URL
              value: jdbc:postgresql://patronidemo:5432/companymanagement
            - name: SPRING_SLEUTH_PROPAGATION_KEYS
              value: "x-request-id,x-ot-span-context"
            - name: SERVER_SHUTDOWN
              value: graceful
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: com.ti.sirh
            - name: ELASTIC_APM_SERVICE_NAME
              value: SIRH_STAGING_COMPANY_MANAGEMENT
            - name: ELASTIC_APM_SERVER_URLS
              value: http://apm-server-apm-http:8200
            - name: SPRING_RABBITMQ_ADDRESSES
              value: "rabbitmqcluster:5672"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmqcluster"
            - name: SPRING_RABBITMQ_VIRTUAL-HOST
              value: techin
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmqcluster-default-user
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmqcluster-default-user
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - name: http
              containerPort: 8081