apiVersion: v1
kind: Service
metadata:
  name: webapp-pay
  namespace: default
  labels:
    app: webapp-pay
spec:
  selector:
    app: webapp-pay
  type: LoadBalancer
  ports:
    - name: http
      port: 8082
