apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.2.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
    
  podTemplate:
      spec:
        nodeSelector:
          node-name: master-3