apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
spec:
  type: NodePort
  selector:
    kibana.k8s.elastic.co/name: kibana
    common.k8s.elastic.co/type: kibana
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5601
      targetPort: 5601
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30100
